### ISSUE TITLE
WebHook test step got error message

### ISSUE THREAD

**Issue by justlight220** [syshen/n8n-nodes-linewebhook#1]
using test step got this error message.
Is any tips can solve it?

Invalid status code: undefined
Error details
`{
  "errorMessage": "Invalid status code: undefined",
  "errorDetails": {},
  "n8nDetails": {
    "n8nVersion": "1.45.1 (Self Hosted)",
    "binaryDataMode": "default",
    "stackTrace": [
      "RangeError: Invalid status code: undefined",
      "    at ServerResponse.writeHead (node:_http_server:352:11)",
      "    at ServerResponse.writeHead (/usr/local/lib/node_modules/n8n/node_modules/on-headers/index.js:44:26)",
      "    at Object.webhook (/home/node/.n8n/nodes/node_modules/n8n-nodes-linewebhook/nodes/LineWebhook/LineWebhook.node.ts:127:9)",
      "    at Workflow.runWebhook (/usr/local/lib/node_modules/n8n/node_modules/n8n-workflow/dist/Workflow.js:665:15)",
      "    at Object.executeWebhook (/usr/local/lib/node_modules/n8n/dist/WebhookHelpers.js:219:33)",
      "    at /usr/local/lib/node_modules/n8n/dist/TestWebhooks.js:99:37"
    ]
  }
}
`
<img width="1223" alt="Screenshot 2024-06-23 at 6 50 19 PM" src="https://github.com/syshen/n8n-nodes-linewebhook/assets/75196944/458eab3e-402f-404b-a143-d4bbc72d8b80">

**Comment by PhantasWeng** [comment]
I encountered the same problem as well
![Google Chrome ⚠️ My workflow - n8n 2024-11-19 at 11 43 58](https://github.com/user-attachments/assets/2171605b-f43c-4d19-bde1-e2fca21e637d)

**Comment by PhantasWeng** [comment]
@syshen Are there any solutions?

**Comment by PhantasWeng** [comment]
> @justlight220 @PhantasWeng Just fix the issue, please upgrade to 0.1.50.

Happy to hear this! I will try it and feedback after.

**Comment by syshen** [comment]
> @syshen It seems that the error has changed. The original undefined error is gone, but now there is no response from the webhook, and the Line Console shows a 500 server error
> 
>  Google.Chrome.Line.Template.-.n8n.2024-11-25.at.12.12.47.mp4 
> Additionally, I can successfully receive it using a regular webhook
> 
>  Google.Chrome.Line.Template.-.n8n.2024-11-25.at.12.17.46.mp4

500 is the expected error, since "test step" doesn't provide Line's auth header.

**Comment by PhantasWeng** [comment]
> > @syshen It seems that the error has changed. The original undefined error is gone, but now there is no response from the webhook, and the Line Console shows a 500 server error
> > Google.Chrome.Line.Template.-.n8n.2024-11-25.at.12.12.47.mp4
> > Additionally, I can successfully receive it using a regular webhook
> > Google.Chrome.Line.Template.-.n8n.2024-11-25.at.12.17.46.mp4
> 
> 500 is the expected error, since "test step" doesn't provide Line's auth header.

I realized that I made a mistake by entering the channel secret instead of the channel ID.

After making the correction, it works now, but currently, the webhook for join and leave events is not triggering. I'm still looking into it.

Would you mind if I help update the README? I can write some instructions.

Additionally, I will delete the video above because it reveals my website URL.
